export const maneuvers = [
  {
    "Name": "Drop ToeHold",
    "Level": 1,
    "Attribute": "Aerial Tactics",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler hooks one of his opponent's legs with one of his own as the attacker falls to the mat, causing the opponent to fall belly-first to the mat. The attacker can now maintain a toehold until broken."
  },
  {
    "Name": "Kick",
    "Level": 1,
    "Attribute": "Aerial Tactics",
    "Standing": "SKPFR",
    "Kneeling": "",
    "Prone": "SKP",
    "Flying": "",
    "Running": "SKPR",
    "Stun Points": "1, power, run",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Kicking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler simply extends one of his legs and hits his opponent with the flat part (or bottom) of it."
  },
  {
    "Name": "Standing on Opponent",
    "Level": 1,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "Attacker's Weight Mod. Stun",
    "Legal": false,
    "Weight Mod": 3,
    "Type": "Punishing",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler simply places both feet on the opponent and stands there."
  },
  {
    "Name": "Bearhug",
    "Level": 1,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler grabs his opponent around the rib cage and squeezes."
  },
  {
    "Name": "Bodyslam",
    "Level": 1,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler bends down, reaches between the opponent's legs, lifts the opponent and throws him down onto his back."
  },
  {
    "Name": "Clothesline",
    "Level": 1,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "SR",
    "Running": "SR",
    "Stun Points": "2, power, run, fly",
    "Legal": true,
    "Weight Mod": 1,
    "Type": "Take Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler extends his arm out away from his body to one side and uses it to hit his opponent across the upper chest and knock him down."
  },
  {
    "Name": "Head Vise",
    "Level": 1,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Standing",
    "Opponent Position After": "Kneeling",
    "Description": "The attacking wrestler places a hand on each side of an opponent's head and squeezes."
  },
  {
    "Name": "Irish-whip into Corner",
    "Level": 1,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Standing",
    "Description": "The attacking wrestler grabs one of his opponent's arms and uses it for leverage to throw his opponent into one of the corners or an object."
  },
  {
    "Name": "Push Down",
    "Level": 1,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Knock Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler pushes on the opponent's chest, back or shoulders with enough force to knock the opponent down."
  },
  {
    "Name": "Shoulderblock",
    "Level": 1,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "SFR",
    "Running": "SR",
    "Stun Points": "2, power, run, fly",
    "Legal": true,
    "Weight Mod": 1,
    "Type": "Take Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler hits his opponent with his shoulder with enough force to knock the opponent to the mat."
  },
  {
    "Name": "Back Fist Strike",
    "Level": 1,
    "Attribute": "Martial Arts",
    "Standing": "SR",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": false,
    "Weight Mod": 16,
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler makes a clenche and hits the opponent in a short upward arm movement."
  },
  {
    "Name": "Claw",
    "Level": 1,
    "Attribute": "Martial Arts",
    "Standing": "SKFR",
    "Kneeling": "SKPFR",
    "Prone": "SKPFR",
    "Flying": "SKPFR",
    "Running": "SKFR",
    "Stun Points": "1, power, run, fly",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler spreads all of his fingers apart and places them on the opponent, usually the head, and applies pressure."
  },
  {
    "Name": "Karate Chop",
    "Level": 1,
    "Attribute": "Martial Arts",
    "Standing": "SFR",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "S",
    "Running": "SR",
    "Stun Points": "1, power, run, fly",
    "Legal": true,
    "Weight Mod": 16,
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler hits his opponent with the outer edge of his flattened hand."
  },
  {
    "Name": "Karate Punch",
    "Level": 1,
    "Attribute": "Martial Arts",
    "Standing": "SKF",
    "Kneeling": "SKPFR",
    "Prone": "",
    "Flying": "SKPFR",
    "Running": "SKPFR",
    "Stun Points": "2, power, run, fly",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler makes a fist with his knuckles curled tightly in the palm of his hand under his thumb and hits the opponent, pulling back the other hand, adding to the snapping motion."
  },
  {
    "Name": "Leg Sweep",
    "Level": 1,
    "Attribute": "Martial Arts",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "S",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Last Position",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler uses one of his legs to knock the feet out from underneath his opponent."
  },
  {
    "Name": "Armlock",
    "Level": 1,
    "Attribute": "Technical Ability",
    "Standing": "",
    "Kneeling": "",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Wear Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places one arm under, then over his opponenets arm in a number-four formation. He then applies pressure."
  },
  {
    "Name": "Armwringer",
    "Level": 1,
    "Attribute": "Technical Ability",
    "Standing": "SKR",
    "Kneeling": "SKP",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "1, power, run, fly",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Wear Down",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler grabs his opponent at the wrist then twists his arm."
  },
  {
    "Name": "Chicken Wing/Hammerlock",
    "Level": 1,
    "Attribute": "Technical Ability",
    "Standing": "S",
    "Kneeling": "KP",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Wear Down",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The tracking wrestler takes one of the opponent's arms and bends it in an 'L' shape behind the opponent and holds it there."
  },
  {
    "Name": "Standing Side Headlock",
    "Level": 1,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Wear Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Kneeling",
    "Description": "The attacking wrestler places his opponent's head under one of his armpits, hooks one of the opponent's legs with his own, falls to his side and holds the opponent in a pinfall predicament."
  },
  {
    "Name": "Single Leg Takedown",
    "Level": 1,
    "Attribute": "Technical Ability",
    "Standing": "",
    "Kneeling": "S",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent's leg at the knee and lifts it high, throwing the opponent off-balance and sending him crashing to the mat."
  },
  {
    "Name": "Bite",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SK",
    "Kneeling": "SKP",
    "Prone": "SKP",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Wear Down",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler opens his mouth and clamps it shut on a part of his opponent's body."
  },
  {
    "Name": "Choke",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SK",
    "Kneeling": "KP",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Wear Down",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler wraps both or one hand around the throat of his opponent and squeezes."
  },
  {
    "Name": "Double Axhandle",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SKFR",
    "Kneeling": "KP",
    "Prone": "",
    "Flying": "SKFR",
    "Running": "SKFR",
    "Stun Points": "2, power, run, fly",
    "Legal": false,
    "Weight Mod": 16,
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Next Lower Position",
    "Description": "The attacking wrestler laces his fingers and makes a clenched fist with both hands. The attacker then hits the opponent in a downward movement. The hits are to the upper back, head and neck."
  },
  {
    "Name": "Eye Gouging",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SK",
    "Kneeling": "KP",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "1 (A)",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Desperation",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler pokes or rakes his opponent's eyes with his fingers."
  },
  {
    "Name": "Hair Pulling",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SKR",
    "Kneeling": "KP",
    "Prone": "P",
    "Flying": "SKF",
    "Running": "SKFR",
    "Stun Points": "1, power, run, fly",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Desperation",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler grabs the opponent by the hair and pulls."
  },
  {
    "Name": "Headbutt",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "S",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "SKPFR",
    "Running": "SFR",
    "Stun Points": "1, run, fly",
    "Legal": true,
    "Weight Mod": 16,
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler hits his opponent with his forehead, usually, on the opponent's head."
  },
  {
    "Name": "Open Hand Punch (Slap)",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SKFR",
    "Kneeling": "SKPFR",
    "Prone": "P",
    "Flying": "SKPFR",
    "Running": "SKFR",
    "Stun Points": "1, power, run, fly",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler hits his opponent with the open palm of his hand."
  },
  {
    "Name": "Punch",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SKFR",
    "Kneeling": "SKPFR",
    "Prone": "P",
    "Flying": "SKPFR",
    "Running": "SKFR",
    "Stun Points": "1, power, run, fly",
    "Legal": false,
    "Weight Mod": 16,
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler hits his opponent with a clenched fist."
  },
  {
    "Name": "Scratching",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "SK",
    "Kneeling": "SKP",
    "Prone": "SKP",
    "Flying": "SK",
    "Running": "",
    "Stun Points": "1, power, fly",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Desperation",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler rakes his fingernails on the opponent."
  },
  {
    "Name": "Stomp",
    "Level": 1,
    "Attribute": "Brawling",
    "Standing": "KP",
    "Kneeling": "",
    "Prone": "",
    "Flying": "KP",
    "Running": "KP",
    "Stun Points": "1, power, run, fly",
    "Legal": false,
    "Weight Mod": 3,
    "Type": "Punishing",
    "Your Position After": "Standing",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler shoves his foot down sharply on the opponent."
  },
  {
    "Name": "Abdominal Splash",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "P",
    "Running": "P",
    "Stun Points": "2, run, fly",
    "Legal": true,
    "Weight Mod": 7,
    "Type": "Punishing",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps in the air and lands his abdomen across the chest of his opponent. This can be done to other parts of the attacked wrestler's body if stated before the maneuver is completed but is normally performed as above."
  },
  {
    "Name": "Big Boot",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "R",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power, run",
    "Legal": true,
    "Weight Mod": 1,
    "Type": "Take Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands, Irish-whips his opponent into the ropes and kicks him in the face as he comes back, knocking the opponent to the mat."
  },
  {
    "Name": "Cross-Bodyblock / Flying Bodypress",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "S",
    "Running": "SR",
    "Stun Points": "2, run, fly",
    "Legal": true,
    "Weight Mod": 8,
    "Type": "Take Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps aan opponent, either standing and facing him or running at the attacker, and throws his abdomen against the opponent's chest, sending the opponent to the mat and the attacker landing on top of him."
  },
  {
    "Name": "Crucifix Pin Maneuver",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 8,
    "Type": "Pinfall",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps at an upright character from behind. The attacker then wraps both arms around one of the opponent's arms and both legs around the opponent's other arm. The attacker then shifts his weight backward, causing his opponent to fall backward in a pinfall predicament."
  },
  {
    "Name": "Double Kick to Head",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 6,
    "Type": "Striking",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps in the air, twists his body to the side and kicks with both feet at the same time to the back of his opponent's head."
  },
  {
    "Name": "Dropkick",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "SFR",
    "Running": "SKFR",
    "Stun Points": "2, power, run, fly",
    "Legal": true,
    "Weight Mod": 6,
    "Type": "Striking",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps in the air and kicks his opponent with both feet."
  },
  {
    "Name": "Drop Punch / Fistdrop",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "P",
    "Running": "P",
    "Stun Points": "2, power, run, fly",
    "Legal": true,
    "Weight Mod": 9,
    "Type": "Striking",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands over his opponent, makes a fist and simply falls forward or leaps in the air, dopping the fist on his opponent's head."
  },
  {
    "Name": "Elbowdrop",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "P",
    "Running": "P",
    "Stun Points": "2, run, fly",
    "Legal": true,
    "Weight Mod": 7,
    "Type": "Striking",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands over his opponent, bends his elbow in an 'L' shape, then falls backward (or on his side), hitting the opponent with his upper arm and elbow area."
  },
  {
    "Name": "Flying Mare",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "2, run, fly",
    "Legal": true,
    "Weight Mod": 5,
    "Type": "Take Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps in the air, quickly wraps both legs around his opponent's neck and falls, flipping the opponent onto his back."
  },
  {
    "Name": "Hamstring Pull",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Punishing",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs one of the downed opponent's legs at the ankle, holds tight and leaps over his opponent's hamstring muscle."
  },
  {
    "Name": "Kneedrop",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "P",
    "Running": "P",
    "Stun Points": "2, run, fly",
    "Legal": true,
    "Weight Mod": 7,
    "Type": "Striking",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands over his opponent, lifts one of his knees parallel to his chest and falls forward, striking the opponent with his knee."
  },
  {
    "Name": "Legdrop",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "P",
    "Running": "P",
    "Stun Points": "2, run, fly",
    "Legal": true,
    "Weight Mod": 7,
    "Type": "Striking",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands over his opponent, extends one of his legs fully away from his body and falls, hitting the opponent with the extended leg."
  },
  {
    "Name": "Monkey Flip Suplex",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 5,
    "Type": "Take Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler is standing and leaps at his opponent, planting both feet in the pit of his standing opponent's stomach. He then grabs the back of the opponents head and flips him in the air."
  },
  {
    "Name": "Vertical Splash (Buttdrop)",
    "Level": 2,
    "Attribute": "Aerial Tactics",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 7,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands over his opponent, leaps in the air and lands backside-first on his opponent's chest."
  },
  {
    "Name": "Karate Kick",
    "Level": 2,
    "Attribute": "Martial Arts",
    "Standing": "SKFR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "SKR",
    "Running": "SKPFR",
    "Stun Points": "2, run, fly",
    "Legal": true,
    "Weight Mod": 16,
    "Type": "Striking",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler chambers the kicking leg, bringing it upward and close to the body, then snaps the foot outward and upward, striking with the heel or edge of the foot."
  },
  {
    "Name": "Knee Armlock",
    "Level": 2,
    "Attribute": "Martial Arts",
    "Standing": "",
    "Kneeling": "",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler twists his opponent's arm, places his knee against it and pulls back, applying pressure."
  },
  {
    "Name": "Leg Wheel",
    "Level": 2,
    "Attribute": "Martial Arts",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler twists his body to grab an opponent that is behind him. He then extends one of his legs across the opponent's thigh and jerks him forward, causing the opponent to flip over the thigh and crash onto his back."
  },
  {
    "Name": "Lunge Punch",
    "Level": 2,
    "Attribute": "Martial Arts",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power, run",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Striking",
    "Your Position After": "Standing",
    "Opponent Position After": "Next Lower Position",
    "Description": "The attacking wrestler leaps forward, pushing off with his feet and hits his opponent in the abdomen and ribs with a clenched fist."
  },
  {
    "Name": "Roundhouse Kick",
    "Level": 2,
    "Attribute": "Martial Arts",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 1,
    "Type": "Striking",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler spins halfway around and kicks his opponent with his foot with all the power he can muster."
  },
  {
    "Name": "Savat Kick / Crescent Kick / Back Kick",
    "Level": 2,
    "Attribute": "Martial Arts",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power, run",
    "Legal": true,
    "Weight Mod": 1,
    "Type": "Kicking",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler back kicks sharply upward and hits the opponent in the area of the throat or under the chin, knocking the opponent down."
  },
  {
    "Name": "U-Punch",
    "Level": 2,
    "Attribute": "Martial Arts",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "SR",
    "Stun Points": "2, power, run",
    "Legal": false,
    "Weight Mod": 16,
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler hits his opponent with two clenched fists simultaneously. One punch is to the chest, the other is to the abdomen."
  },
  {
    "Name": "Armbar",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "SK",
    "Kneeling": "KP",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Wear Down",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler grabs his opponent's arm at the wrest and twists. The attacker then places one forearm across the opponent's twisted arm and pulls it downward with his other arm in a number-four shape."
  },
  {
    "Name": "Armbar Takedown",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "SR",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "S",
    "Running": "",
    "Stun Points": "1, run, fly",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler hooks his opponent's arm with his own, falls to one knee and throws his opponent over the attacker's back onto his opponent's back."
  },
  {
    "Name": "Drop DDT",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The tracking wrestler places his opponent's head under his arm so that the body of his opponent is in front of him. The attacker then throws himself onto his back, sending his opponent's head crashing against the mat."
  },
  {
    "Name": "Fireman Carry Takedown",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "",
    "Kneeling": "S",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler reaches between his opponent's legs with one arm, throws the opponent off balance, grabs the back of his head until he starts teetering and flips him across the attacker's shoulder onto his back."
  },
  {
    "Name": "Half Nelson",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "S",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "The attacking wrestler takes one arm and reaches up underneath the opponent's armpit from behind. The attacker then places his hand behind the opponent's neck and applies pressure."
  },
  {
    "Name": "Half Nelson Sleeper",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "S",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Knockout",
    "Your Position After": "Last Position",
    "Opponent Position After": "Last Position",
    "Description": "From behind his opponent, the attacking wrestler places one arm under his opponent's arm and around his neck. Next he places the other arm around the opposite side of the opponent's neck and grabs his own arm at the elbow. The attacker veins squeezing his opponent until he passes out."
  },
  {
    "Name": "Hip Toss",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler hooks his arm under the armpit of an opponent who is standing behind him and tosses the opponent over his hip onto his back."
  },
  {
    "Name": "Neckbreaker",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "K",
    "Stun Points": "3, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs a doubled-over opponent by the neck so that his body is behind him and holds it at his side. The attacker then throws himself and his opponent on his side, wrenching the opponent's neck."
  },
  {
    "Name": "Reverse Neckbreaker",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "K",
    "Stun Points": "3, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler is standing and places a kneeling opponent's head at his side and holds it there with one arm. The attacker then throws himself onto his back sideways so that the opponent's neck is wrenched as both characters fall to the mat."
  },
  {
    "Name": "Rollup",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "SK",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "Pinfall",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places one arm behind the head of the opponent and hooks one of his legs with the other. The attacker then falls backward, rolling the opponent0s shoulders to the mat."
  },
  {
    "Name": "Side Russian Leg Sweep",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands side-by-side with his opponent, places one of his attacker's arms around his own neck, places one of his arms around the opponent's neck, hooks the opponent's legs with one of his own, then falls backward, slamming the opponent into the mat."
  },
  {
    "Name": "Small Package",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Pinfall",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places his opponent's head under one of his armpits, hooks one of the opponent's legs with his own, falls to his side and holds the opponent in a pinfall predicament."
  },
  {
    "Name": "Snapmare",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler reaches behind himself with one hand to grab the opponent (standing behind him) by the neck. The attacker then drops to one knee and flips the opponent over his shoulder onto the opponent's back."
  },
  {
    "Name": "Sunset Flip",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "SK",
    "Running": "K",
    "Stun Points": "1, run, fly",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Pinfall",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler flips over the back of a doubled-over opponent, falls onto his back, grabbing both of the opponent's thighs on his way down and pulls the opponent over onto his back in a pinfall predicament."
  },
  {
    "Name": "Toehold",
    "Level": 2,
    "Attribute": "Technical Ability",
    "Standing": "",
    "Kneeling": "P",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler (standing) takes one of a prone positioned opponent's legs, extends it upward and twists it at the foot."
  },
  {
    "Name": "Airplane Spin and Slam",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, (H)",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent onto his shoulders and spins around. This causes the opponent to get dizzy and the opponent can't block the next attack. The attacking wrestler then throws his opponent to the mat or floor."
  },
  {
    "Name": "Atomic Drop",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Standing",
    "Description": "The attacking wrestler lifts his opponent at the waist from behind so the opponent's back is parallel to the mat. He then drops his opponent forward, drops to one knee and extends the other between his opponent's legs. The opponent's backside will hit the attacker's knee."
  },
  {
    "Name": "Body Scissors",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "",
    "Kneeling": "",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler sits next to his opponent and wraps his legs around the opponent, crossing their ankles and then tightening their grip by squeezing together their thighs or straightening their legs to compress the opponent's torso."
  },
  {
    "Name": "Fallaway Bodyslam",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent across his chest, then falls forward with him."
  },
  {
    "Name": "Front Elbow Block",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "R",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "SR",
    "Stun Points": "2, power, run",
    "Legal": true,
    "Weight Mod": 1,
    "Type": "Take Down",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler hits the opponent in the head area with his elbow and forearm."
  },
  {
    "Name": "Gorilla Press Slam",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent over his head with his arms fully extended and drops him head onto his back."
  },
  {
    "Name": "Gut Wrench Suplex",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent at the waist, lifts him and slams him on his back as hard as he can."
  },
  {
    "Name": "Hair Pull Lift-and-Slam",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Power",
    "Your Position After": "Prone",
    "Opponent Position After": "Standing",
    "Description": "The attacking wrestler grabs a sitting wrestler by the hair, lifts him off the ground by his hair and throws him down on his back."
  },
  {
    "Name": "Head into Object Smash",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "K",
    "Prone": "P",
    "Flying": "SR",
    "Running": "SR",
    "Stun Points": "Object, power, run, fly",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Pinfall",
    "Your Position After": "Last Position",
    "Opponent Position After": "Next Lower Position",
    "Description": "The attacking wrestler grabs the back of his opponent's head and slams it into an object."
  },
  {
    "Name": "Head Scissors",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "",
    "Kneeling": "",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler wraps both his legs around the opponent's head and squeezes."
  },
  {
    "Name": "Head-to-Mat Smash",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "K",
    "Prone": "P",
    "Flying": "SR",
    "Running": "SR",
    "Stun Points": "2, power, run, fly",
    "Legal": false,
    "Weight Mod": 10,
    "Type": "Pinfall",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs the backs of his opponent's head and slams it into the mat."
  },
  {
    "Name": "Inverted Atomic Drop",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent, who is facing him, at the waist and drops the opponent's backside across his knee."
  },
  {
    "Name": "Irish-whip into Object",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power, object stun code",
    "Legal": false,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs one of his opponent's arms and uses it for leverage to throw his opponent into one of the corners or an object."
  },
  {
    "Name": "Power Choke",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": false,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking opponent wrestler grabs an opponent by the neck, lifts him into the air off his feet and holds him there with his arms fully extended, choking him."
  },
  {
    "Name": "Reverse Fallaway Bodyslam",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places his opponent across his shoulders and falls backward, causing the attacker to flip over the opponent."
  },
  {
    "Name": "Scoop Side Suplex",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "R",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts a running opponent at the waist, quickly shifts the opponent's body so his back is parallel to the mat and slams him down to the mat."
  },
  {
    "Name": "Shoulder Backbreaker",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Submission",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent by the shoulder then extends one of his legs and slams the opponent's upper back onto the extended knee."
  },
  {
    "Name": "Side Suplex",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "",
    "Kneeling": "SR",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent at the waist, shifts the opponent's weight so his back is parallel to the mat and slams him down to the mat."
  },
  {
    "Name": "Single Leg Pickup",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "",
    "Kneeling": "SR",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent's leg near the ankle and lifts it high, throwing the opponent off-balance and sending him crashing to the mat."
  },
  {
    "Name": "Snap Suplex",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler is standing and facing a kneeling opponent. The attacker takes one of the opponent's arms and wraps it around his neck. The attacker then reaches down and grabs the opponent by the thigh. The attacker then falls backward sharply, causing the opponent to flip over on his back."
  },
  {
    "Name": "Through-the-Ropes Toss",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "R",
    "Stun Points": "4, floor, run",
    "Legal": false,
    "Weight Mod": 2,
    "Type": "Pinfall",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent by the back of the head and throws him between the second and top ropes to the ringside floor."
  },
  {
    "Name": "Vertical Suplex",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "Both wrestlers are facing each other. The attacking wrestler places one of the opponent's arms around his neck, lifts him so his feet are pointing directly skyward, then falls backward so the opponent lands on his back."
  },
  {
    "Name": "Waistlock / Side-Walk Slam",
    "Level": 2,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "R",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler (standing) grabs his opponent (standing or running) at the waist and lifts him. Both characters are facing each other. The attacker then falls forward, slamming the opponent's back to the mat and crashing down on top of the opponent as well."
  },
  {
    "Name": "Corner Piston Punch (2 punches)",
    "Level": 2,
    "Attribute": "Brawling",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Punishing",
    "Your Position After": "Standing",
    "Opponent Position After": "Standing",
    "Description": "The attacking wrestler stands his opponent in one of the corners, climbs to the second rope and begins punching the opponent in the head."
  },
  {
    "Name": "Discus Punch",
    "Level": 2,
    "Attribute": "Brawling",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "SR",
    "Stun Points": "2, power, run",
    "Legal": false,
    "Weight Mod": 1,
    "Type": "Striking",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler spins 360 degrees in a circle and punches his opponent with a closed fist to the head."
  },
  {
    "Name": "Jaw Breaker",
    "Level": 2,
    "Attribute": "Brawling",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Punishing",
    "Your Position After": "Standing",
    "Opponent Position After": "Kneeling",
    "Description": "The attacking wrestler pulls his opponent's jaw on top of his head by pulling on his ears and then sits down sharply, slamming his opponent's jaw against the top of his head."
  },
  {
    "Name": "Wrist Spike",
    "Level": 2,
    "Attribute": "Brawling",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1, power",
    "Legal": true,
    "Weight Mod": 3,
    "Type": "Punishing",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler (standing) places a prone wrestler's palm against the mat, places his elbow so it is facing straight up, then presses downward on the elbow with one foot, driving the wrist into the mat."
  },
  {
    "Name": "Lou Thesz Press",
    "Level": 3,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "SR",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "Pinfall",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps at a character that is running toward him, leaps in the air so that both of  his knees are at the sides of the opponent and crashes down onto the opponent in a pinfall position."
  },
  {
    "Name": "Scissors Piledriver",
    "Level": 3,
    "Attribute": "Aerial Tactics",
    "Standing": "R",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3, run",
    "Legal": true,
    "Weight Mod": 8,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler Irish-whips his opponent, leaps in the air, wraps both legs around the opponent's neck, then falls backward, slamming the opponent onto his own head."
  },
  {
    "Name": "Shoulder Roll",
    "Level": 3,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "P",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 3,
    "Type": "Pinfall",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler runs at a downed opponent, falls to one side, driving his shoulder into the opponent's abdomen."
  },
  {
    "Name": "Jumping Spin Kick",
    "Level": 3,
    "Attribute": "Martial Arts",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 5,
    "Type": "Kicking",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler leaps at his opponent, spinning and slinging his leg in a circular motion and hitting the opponent with his foot in the upper chest area."
  },
  {
    "Name": "Spring Punch",
    "Level": 3,
    "Attribute": "Martial Arts",
    "Standing": "SFR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power, run",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Striking",
    "Your Position After": "Standing",
    "Opponent Position After": "Next Lower Position",
    "Description": "The attacking wrestler punches the opponent with both fists simultaneously."
  },
  {
    "Name": "Abdominal Stretch",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Standing",
    "Opponent Position After": "Kneeling",
    "Description": "The attacking wrestler grabs his opponent from behind. He then reaches around the opponent's body with one of his legs and hooks that leg between his opponent's legs. The attacker then takes one of his opponent's arms and wraps it around his neck. This hyberextends the abdominal muscles."
  },
  {
    "Name": "Backdrop",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler bends over, quickly places both hands on the opponent's thighs, stands and throws the opponent over his back, causing the opponent to crash to the mat."
  },
  {
    "Name": "Backslide",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "S",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 11,
    "Type": "Pinfall",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands back-to-back with his opponent. He then hooks both of the opponent's arms with his own and bends forwards. This causes the opponent to slide down the attacker's back in a pinfall position."
  },
  {
    "Name": "Double Underhook Powerbomb",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler is standing in front of a kneeling opponent. The attacker then hammerlocks both of the opponent's arms behind the opponent's back. The attacker then lifts the opponen by his arms, twists him in mid-air so his back is parallel with the mat, than slams his back and neck into the mat."
  },
  {
    "Name": "Full Nelson",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "SK",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Last Position",
    "Opponent Position After": "Next Lower Position",
    "Description": "The attacking wrestler reaches both arms under the armpits of his opponent from behind. The attacker then places both of his hands behind the neck of the opponent, locks the fingers and squeezes."
  },
  {
    "Name": "Rolling Cradle",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "K",
    "Stun Points": "1, run",
    "Legal": true,
    "Weight Mod": 11,
    "Type": "Pinfall",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places one arm around a running opponent's neck and the other around the back of one of his legs. The attacking wrestler then falls, rolling the opponent into a pinfall position."
  },
  {
    "Name": "Sleeper",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "SKR",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "SR",
    "Stun Points": "3, power, run",
    "Legal": true,
    "Weight Mod": 12,
    "Type": "Knockout",
    "Your Position After": "Last Position",
    "Opponent Position After": "Next Lower Position",
    "Description": "The attacking wrestler grabs the opponent from behind, places one arm across the opponent's forehead, places the other arm underneath the opponent's chin, grabs his forearm with the arm under the chin and applies pressure."
  },
  {
    "Name": "Slingshot Catapult into Corner",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3",
    "Legal": true,
    "Weight Mod": 11,
    "Type": "Pinfall",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler (standing) grabs a prone opponent that is on his back by the legs, places one under each arm and falls backwards, causing the opponent to rise up and be catapulted into the corner turnbuckle."
  },
  {
    "Name": "Step-Over Toehold",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler takes one of the opponent's legs, wraps it around his own legs and holds it, applying pressure."
  },
  {
    "Name": "Tilt-a-Whirl Backbreaker",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "R",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent by the waist, spins him around twice so his back is parallel to the mat, extends one of his legs and slams the opponent's upper back onto the extended knee."
  },
  {
    "Name": "Tilt-a-Whirl Slam",
    "Level": 3,
    "Attribute": "Technical Ability",
    "Standing": "R",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power, run",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent by the waist, spins him around twice so his back is parallel to the mat and slams the opponent's upper back onto the mat."
  },
  {
    "Name": "Backbreaker Torture Rack",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3, power",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Submission",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent onto his shoulders. His oppondnet will be facing the ceiling while on his shoulders and his back will be across the attacker's back, near his neck. The two will look like a cross. The attacker will thnegin pulling downward on the opponent's neck and thighs, causing pressure on the opponent's back."
  },
  {
    "Name": "Belly-to-Back Suplex",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Take Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs the opponent at the waist while standing in front of his opponent. The attacker then falls backward sharply, pivots on one foot and slams the opponent onto his back and shoulders with the attacker falling on top of the opponent."
  },
  {
    "Name": "Camel Clutch Reverse Chinlock",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "",
    "Kneeling": "",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": 3,
    "Type": "Submission",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler sits on his opponent's back, reaches forward and locks his fingers underneath his opponent's chin. The attacker then pulls back with his arms."
  },
  {
    "Name": "Corner Clothesline",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "2, run",
    "Legal": false,
    "Weight Mod": 13,
    "Type": "Pinfall",
    "Your Position After": "Standing",
    "Opponent Position After": "Standing",
    "Description": "The attacking wrestler stands his opponent in one of the corners or up against an object. The attacker then goes to the opposite corner or at least four spaces away and runs at his opponent full speed. The attacker extends his arm out away from his body and hits his opponent as in a clothesline maneuver."
  },
  {
    "Name": "Cradle Suplex / German Suplex",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "Pinfall",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler gabs one of the opponent's arms and places it around his neck. The attacker then leans forward and grabs one of the attacker's thighs. Marishs. The attacker then falls backward and arches (or bridges) his back, placing the opponent in a pinfall position."
  },
  {
    "Name": "Crucifix Shoulderslam",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent onto his hack so that the two characters are back-to-back. The attacker then extends his and the opponent's arms in a crucifix pattern. The attacker then falls forward, driving the opponent's head and neck into the mat."
  },
  {
    "Name": "One-Handed Choke Slam",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "SR",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power, run",
    "Legal": false,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs the opponent by the neck with one hand. He then lifts the opponent and slams him down onto his back."
  },
  {
    "Name": "Powerslam",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "R",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler throws his opponent into the ropes, catches him after he bounces off the ropes by reaching one hand between his legs and the other around his neck/shoulder area, pivots on one foot, twists his body to the side as he pivots and slams the opponent to the mat on his back with the attacker falling on top of him."
  },
  {
    "Name": "Side Mare Headlock Takedown",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "K",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "1",
    "Legal": true,
    "Weight Mod": 4,
    "Type": "Take Down",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places the opponent's head at his side, drops to one knee, flips his opponent onto his back and continues to squeeze with a side headlock in the kneeling (attacker) and prone (opponent) positions."
  },
  {
    "Name": "Tights Pull Through the Ropes",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "",
    "Kneeling": "S",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "4, floor",
    "Legal": false,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler (kneeling) grabs a standing opponent by the tights, falls backward and uses the leverage to throw the opponent through the second and top ropes to the ringside floor."
  },
  {
    "Name": "Tombstone Piledriver",
    "Level": 3,
    "Attribute": "Brute Strength",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler (standing) grabs the opponent at the waist, turns the opponent so his belly is against the attacker's body, places the opponet's head between his knees, then drops to his knees, driving the opponent's head into the mat."
  },
  {
    "Name": "Piston Punch (3 punches)",
    "Level": 3,
    "Attribute": "Brawling",
    "Standing": "",
    "Kneeling": "P",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3, power",
    "Legal": false,
    "Weight Mod": "",
    "Type": "Pinfall",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler punches the opponent three times in rapid succession."
  },
  {
    "Name": "Windup Punch",
    "Level": 3,
    "Attribute": "Brawling",
    "Standing": "SK",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": false,
    "Weight Mod": 2,
    "Type": "Striking",
    "Your Position After": "Last Position",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler makes a clenched fist, spins it in a circle several times, then hits the opponent with the fist."
  },
  {
    "Name": "Avalanche",
    "Level": 4,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 13,
    "Type": "Pinfall",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The opponent is standing in one of the corners or up against any object such as a ringpost. The attacking wrestler stands in the opposite corner or at leastfour squares away and runs directly at his opponent, crashing into him with his body."
  },
  {
    "Name": "Over-Top-Rope Cross-Bodyblock",
    "Level": 4,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "7, floor, run",
    "Legal": false,
    "Weight Mod": 15,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands his opponent against the ropes. He then backs up, runs at the opponent, leaps in the air and hits the opponent in the area of the chest with his own chest. The force of the impact will send both characters over the top rope to the floor. The attacking character will take no stun for the fall because he is controlling the fall."
  },
  {
    "Name": "Through-the-Ropes-Leap Cross-Bodyblock",
    "Level": 4,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "6, floor",
    "Legal": false,
    "Weight Mod": 15,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler runs at an opponent standing at ringside. The attacker then leaps between the top and second ropes and performs a Cross-Bodyblock on the opponent at ringside."
  },
  {
    "Name": "Through-the-Ropes-Leap and Clothesline",
    "Level": 4,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "6, floor, run",
    "Legal": false,
    "Weight Mod": 15,
    "Type": "High Impact",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler runs at an opponent standing at ringside. The attacker then leaps between the top and second ropes and clotheslines the opponent at ringside."
  },
  {
    "Name": "Vertical / Earthquake Splash",
    "Level": 4,
    "Attribute": "Aerial Tactics",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "P",
    "Stun Points": "3, run",
    "Legal": true,
    "Weight Mod": 7,
    "Type": "Pinfall",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands over his opponent, leaps in the air and lands backside-first on his opponent's chest."
  },
  {
    "Name": "Figure-Four Armlock",
    "Level": 4,
    "Attribute": "Martial Arts",
    "Standing": "",
    "Kneeling": "",
    "Prone": "P",
    "Flying": "",
    "Running": "",
    "Stun Points": "2, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler takes one of the arms of a downed opponent and wraps it around one of his own arms. The attacking wrestler then falls on his back and hooks his arm over the opponent's arm so it appears to be in the number four configuration. The attacking wrestler then applies pressure."
  },
  {
    "Name": "Boston Crab",
    "Level": 4,
    "Attribute": "Technical Ability",
    "Standing": "",
    "Kneeling": "P",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3, power",
    "Legal": true,
    "Weight Mod": 14,
    "Type": "Submission",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler takes both legs of an opponent in the prone position on his stomach, places a foot under each armpit and leans backward to apply pressure to the opponent's lower back."
  },
  {
    "Name": "Bulldog",
    "Level": 4,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "K",
    "Stun Points": "2, run",
    "Legal": true,
    "Weight Mod": 8,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places his opponent's head under one arm, then runs forward. The attacker then leaps in the air and falls to the mat, slamming the opponent's head onto the mat or an object."
  },
  {
    "Name": "Figure-Four Leglock",
    "Level": 4,
    "Attribute": "Technical Ability",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3, power",
    "Legal": true,
    "Weight Mod": "",
    "Type": "Submission",
    "Your Position After": "Prone",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler takes one of the legs of a downed opponent and wraps it around one of his own legs. The attacking wrestler then falls on his back and hooks his leg over the opponent's leg so it appears to be in the number four configuration. The attacking wrestler then applies pressure."
  },
  {
    "Name": "Piledriver",
    "Level": 4,
    "Attribute": "Technical Ability",
    "Standing": "K",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "High Impact",
    "Your Position After": "Kneeling",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler places his kneeling opponent's head between his legs and lifts the opponent at the waist so the opponent's head is pointing downward and his feet are pointing straight up. The attacker then sits down sharply, ramming the opponent's head into the mat. This maneuver is so dangerous that it is banned in many places."
  },
  {
    "Name": "Standing Figure-Four Leglock",
    "Level": 4,
    "Attribute": "Technical Ability",
    "Standing": "P",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "3",
    "Legal": true,
    "Weight Mod": 14,
    "Type": "Submission",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs his opponent's legs while the opponent is on his back and wraps them around his own in a number four configuration. The attacking wrestler then flips the opponent over onto his stomach and leans backward, applying pressure to the legs and lower back."
  },
  {
    "Name": "Gorilla Press Drop Over the Top Rope",
    "Level": 4,
    "Attribute": "Brute Stregth",
    "Standing": "S",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "",
    "Stun Points": "5, floor",
    "Legal": true,
    "Weight Mod": 2,
    "Type": "Power",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler lifts his opponent over his head with his arms fully extended and drops him over the top rope to the ringside area."
  },
  {
    "Name": "Over-Top-Rope Clothesline",
    "Level": 4,
    "Attribute": "Brute Stregth",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "S",
    "Stun Points": "7, floor, run",
    "Legal": false,
    "Weight Mod": 2,
    "Type": "Pinfall",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler stands his opponent against the ropes. He then backs up, runs at his opponent, extends one of his arms and hits the opponent at the collar bone sending the opponent over the top rope to the floor."
  },
  {
    "Name": "Over-Top-Rope Toss",
    "Level": 4,
    "Attribute": "Brute Stregth",
    "Standing": "",
    "Kneeling": "",
    "Prone": "",
    "Flying": "",
    "Running": "R",
    "Stun Points": "5, floor, run",
    "Legal": "DQ",
    "Weight Mod": 2,
    "Type": "Pinfall",
    "Your Position After": "Standing",
    "Opponent Position After": "Prone",
    "Description": "The attacking wrestler grabs the opponent by the back of the head, then runs with him side by side and throws him over the top rope to the floor."
  }
]